import { Product } from './store'

export const products: Product[] = [
  // Electronics
  {
    id: 'elec-001',
    name: 'Premium Wireless Noise-Canceling Headphones',
    description: 'Experience immersive audio with our flagship wireless headphones featuring advanced active noise cancellation, 40-hour battery life, and premium memory foam ear cushions for all-day comfort.',
    price: 105.99,
    originalPrice: 349.99,
    category: 'Electronics',
    subcategory: 'Audio',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 2456,
    inStock: true,
    specifications: {
      'Driver Size': '40mm',
      'Frequency Response': '20Hz - 20kHz',
      'Battery Life': '40 hours',
      'Bluetooth Version': '5.2',
      'Weight': '250g',
      'Noise Cancellation': 'Active Hybrid ANC',
    },
    features: [
      'Advanced Active Noise Cancellation',
      'Premium Hi-Res Audio',
      '40-hour battery life',
      'Comfortable memory foam cushions',
      'Multipoint connection',
      'Built-in voice assistant',
    ],
    badge: 'bestseller',
  },
  {
    id: 'elec-002',
    name: '4K Ultra HD Smart Monitor 32"',
    description: 'Professional-grade 4K monitor with HDR10 support, 144Hz refresh rate, and USB-C connectivity. Perfect for creative professionals and gamers alike.',
    price: 149.99,
    originalPrice: 649.99,
    category: 'Electronics',
    subcategory: 'Monitors',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
      'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 1823,
    inStock: true,
    specifications: {
      'Resolution': '3840 x 2160 (4K UHD)',
      'Refresh Rate': '144Hz',
      'Panel Type': 'IPS',
      'Response Time': '1ms',
      'HDR': 'HDR10',
      'Connectivity': 'HDMI 2.1, DisplayPort 1.4, USB-C',
    },
    features: [
      '4K Ultra HD Resolution',
      '144Hz refresh rate for smooth visuals',
      'HDR10 support',
      'USB-C with 90W power delivery',
      'Built-in KVM switch',
      'Ergonomic stand with height adjustment',
    ],
    badge: 'trending',
  },
  {
    id: 'elec-003',
    name: 'Compact Bluetooth Speaker',
    description: 'Portable waterproof Bluetooth speaker with 360-degree sound, 24-hour playtime, and rugged design perfect for outdoor adventures.',
    price: 79.99,
    category: 'Electronics',
    subcategory: 'Audio',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
      'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 3421,
    inStock: true,
    specifications: {
      'Output Power': '20W',
      'Battery Life': '24 hours',
      'Waterproof Rating': 'IP67',
      'Bluetooth Version': '5.0',
      'Weight': '540g',
      'Dimensions': '180 x 75mm',
    },
    features: [
      '360-degree immersive sound',
      'IP67 waterproof and dustproof',
      '24-hour battery life',
      'Built-in microphone for calls',
      'Pair two speakers for stereo',
      'Rugged design',
    ],
    badge: 'new',
  },
  {
    id: 'elec-004',
    name: 'Mechanical Gaming Keyboard RGB',
    description: 'Premium mechanical keyboard with hot-swappable switches, per-key RGB lighting, and aircraft-grade aluminum frame.',
    price: 42.99,
    originalPrice: 189.99,
    category: 'Electronics',
    subcategory: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&q=80',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80',
    ],
    rating: 4.9,
    reviewCount: 2187,
    inStock: true,
    specifications: {
      'Switch Type': 'Hot-swappable Mechanical',
      'Keycaps': 'PBT Double-shot',
      'Backlighting': 'Per-key RGB',
      'Connection': 'USB-C, Wireless 2.4GHz, Bluetooth',
      'Battery Life': '200 hours (no RGB)',
      'Frame Material': 'Aluminum',
    },
    features: [
      'Hot-swappable switches',
      'Per-key RGB with 16.8M colors',
      'Triple connectivity modes',
      'PBT double-shot keycaps',
      'N-key rollover',
      'Onboard memory for profiles',
    ],
    badge: 'bestseller',
  },
  {
    id: 'elec-005',
    name: 'Wireless Charging Pad 3-in-1',
    description: 'Elegant 3-in-1 wireless charging station for smartphone, smartwatch, and earbuds with fast charging support.',
    price: 20.99,
    category: 'Electronics',
    subcategory: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1586816879360-004f5b0c51e5?w=800&q=80',
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 1567,
    inStock: true,
    specifications: {
      'Phone Charging': '15W Fast Charge',
      'Watch Charging': '5W',
      'Earbuds Charging': '5W',
      'Input': 'USB-C 30W',
      'Material': 'Aluminum + Leather',
      'Compatibility': 'Qi-certified devices',
    },
    features: [
      'Charge 3 devices simultaneously',
      '15W fast charging for phones',
      'Compatible with all Qi devices',
      'LED indicator lights',
      'Premium aluminum and leather design',
      'Overcharge protection',
    ],
  },
  {
    id: 'elec-006',
    name: 'Portable External SSD 2TB',
    description: 'Ultra-fast portable SSD with read speeds up to 2000MB/s, compact design, and hardware encryption.',
    price: 139.99,
    originalPrice: 229.99,
    category: 'Electronics',
    subcategory: 'Storage',
    images: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&q=80',
      'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 1234,
    inStock: true,
    specifications: {
      'Capacity': '2TB',
      'Read Speed': 'Up to 2000MB/s',
      'Write Speed': 'Up to 1900MB/s',
      'Interface': 'USB 3.2 Gen 2x2',
      'Encryption': '256-bit AES Hardware',
      'Dimensions': '110 x 55 x 10mm',
    },
    features: [
      'Blazing fast 2000MB/s read speeds',
      'Hardware encryption for security',
      'Compact pocket-sized design',
      'Shock and vibration resistant',
      'Compatible with PC, Mac, and consoles',
      '5-year warranty',
    ],
    badge: 'sale',
  },
  // Smart Gadgets
  {
    id: 'smart-001',
    name: 'Smart Home Hub Pro',
    description: 'Central smart home controller with voice assistant, touchscreen display, and compatibility with 1000+ smart devices.',
    price: 109.99,
    category: 'Smart Gadgets',
    subcategory: 'Home Automation',
    images: [
      'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&q=80',
      'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 987,
    inStock: true,
    specifications: {
      'Display': '8-inch HD Touchscreen',
      'Connectivity': 'WiFi 6, Bluetooth 5.0, Zigbee, Z-Wave',
      'Voice Assistant': 'Built-in',
      'Compatible Devices': '1000+',
      'Power': 'AC Adapter',
      'Dimensions': '200 x 130 x 25mm',
    },
    features: [
      'Control all smart devices from one place',
      '8-inch HD touchscreen',
      'Voice control built-in',
      'Automation routines',
      'Energy monitoring',
      'Intercom functionality',
    ],
    badge: 'trending',
  },
  {
    id: 'smart-002',
    name: 'Smart Fitness Watch Pro',
    description: 'Advanced fitness smartwatch with GPS, heart rate monitoring, sleep tracking, and 14-day battery life.',
    price: 79.99,
    originalPrice: 299.99,
    category: 'Smart Gadgets',
    subcategory: 'Wearables',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 3456,
    inStock: true,
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery Life': '14 days',
      'Water Resistance': '5ATM',
      'GPS': 'Built-in GPS + GLONASS',
      'Sensors': 'Heart Rate, SpO2, Accelerometer',
      'Compatibility': 'iOS & Android',
    },
    features: [
      'Built-in GPS tracking',
      '24/7 heart rate monitoring',
      'Sleep quality analysis',
      'Over 100 workout modes',
      'Smart notifications',
      '5ATM water resistance',
    ],
    badge: 'bestseller',
  },
  {
    id: 'smart-003',
    name: 'Smart Security Camera 4K',
    description: 'Indoor/outdoor security camera with 4K resolution, color night vision, and AI-powered motion detection.',
    price: 61.99,
    category: 'Smart Gadgets',
    subcategory: 'Security',
    images: [
      'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=800&q=80',
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 2134,
    inStock: true,
    specifications: {
      'Resolution': '4K Ultra HD',
      'Night Vision': 'Color Night Vision',
      'Field of View': '160°',
      'Storage': 'Cloud + Local SD',
      'Weather Resistance': 'IP66',
      'Power': 'Wired or Battery',
    },
    features: [
      '4K crystal clear video',
      'Color night vision up to 30ft',
      'AI-powered person detection',
      'Two-way audio',
      'Works with smart home systems',
      'Local and cloud storage options',
    ],
    badge: 'new',
  },
  {
    id: 'smart-004',
    name: 'Smart Doorbell with Camera',
    description: 'Video doorbell with HD camera, two-way audio, motion detection, and smartphone notifications.',
    price: 115.99,
    category: 'Smart Gadgets',
    subcategory: 'Security',
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80',
      'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 1876,
    inStock: true,
    specifications: {
      'Resolution': '2K HDR',
      'Field of View': '180° diagonal',
      'Night Vision': 'Infrared',
      'Power': 'Wired or Battery',
      'Storage': 'Cloud subscription',
      'Connectivity': 'WiFi',
    },
    features: [
      '2K HDR video quality',
      '180° wide-angle view',
      'Advanced motion detection',
      'Two-way talk',
      'Package detection',
      'Quick replies',
    ],
  },
  {
    id: 'smart-005',
    name: 'Smart Air Quality Monitor',
    description: 'Real-time air quality monitoring for PM2.5, CO2, temperature, and humidity with smartphone app.',
    price: 69.99,
    category: 'Smart Gadgets',
    subcategory: 'Health',
    images: [
      'https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?w=800&q=80',
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80',
    ],
    rating: 4.4,
    reviewCount: 654,
    inStock: true,
    specifications: {
      'Sensors': 'PM2.5, CO2, Temperature, Humidity',
      'Display': 'E-ink',
      'Battery': 'Rechargeable',
      'App': 'iOS & Android',
      'Connectivity': 'WiFi, Bluetooth',
      'Accuracy': '±3%',
    },
    features: [
      'Monitor 4 air quality metrics',
      'E-ink display for readings',
      'Historical data tracking',
      'Smart home integration',
      'Rechargeable battery',
      'Compact portable design',
    ],
  },
  
  // Home & Kitchen
  
  {
    id: 'home-002',
    name: 'Smart Air Fryer XL',
    description: 'Large capacity digital air fryer with 10 cooking presets, non-stick basket, and touch controls.',
    price: 129.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    images: [
      'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80',
      'https://images.unsplash.com/photo-1648655652062-270ab29e4a94?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 2876,
    inStock: true,
    specifications: {
      'Capacity': '6.5 Quart',
      'Power': '1700W',
      'Temperature Range': '170°F - 400°F',
      'Presets': '10 cooking modes',
      'Display': 'Digital touchscreen',
      'Basket': 'Non-stick, dishwasher safe',
    },
    features: [
      'Extra large 6.5 quart capacity',
      '10 one-touch cooking presets',
      'Rapid air circulation technology',
      'Digital touchscreen controls',
      'Dishwasher safe basket',
      'Auto shut-off safety feature',
    ],
    badge: 'trending',
  },
  {
    id: 'home-003',
    name: 'Premium Knife Set 15-Piece',
    description: 'Professional kitchen knife set with high-carbon stainless steel blades and wooden block.',
    price: 39.99,
    category: 'Home & Kitchen',
    subcategory: 'Cutlery',
    images: [
      'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80',
      'https://images.unsplash.com/photo-1566454419290-57a0589c9b17?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 876,
    inStock: true,
    specifications: {
      'Pieces': '15',
      'Blade Material': 'High-carbon Stainless Steel',
      'Handle Material': 'Pakkawood',
      'Block Material': 'Acacia Wood',
      'Edge': 'Hand-sharpened 15° angle',
      'Includes': '8 knives, 6 steak knives, shears, block',
    },
    features: [
      'High-carbon stainless steel blades',
      'Razor-sharp 15° edge',
      'Ergonomic Pakkawood handles',
      'Full tang construction',
      'Beautiful acacia wood block',
      'Lifetime warranty',
    ],
  },
  {
    id: 'home-004',
    name: 'Ceramic Non-Stick Cookware Set',
    description: '12-piece ceramic non-stick cookware set with heat-resistant handles and tempered glass lids.',
    price: 99.99,
    originalPrice: 299.99,
    category: 'Home & Kitchen',
    subcategory: 'Cookware',
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
      'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 1543,
    inStock: true,
    specifications: {
      'Pieces': '12',
      'Coating': 'Diamond-infused ceramic',
      'Base': 'Aluminum with steel base',
      'Handles': 'Stainless steel, heat-resistant',
      'Lids': 'Tempered glass',
      'Oven Safe': 'Up to 500°F',
    },
    features: [
      'PFOA and PTFE free',
      'Diamond-infused ceramic coating',
      'Even heat distribution',
      'Compatible with all cooktops',
      'Oven safe to 500°F',
      'Dishwasher safe',
    ],
    badge: 'sale',
  },
  {
    id: 'home-005',
    name: 'Smart Blender Pro',
    description: 'High-performance smart blender with variable speed, self-cleaning, and pre-programmed settings.',
    price: 119.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&q=80',
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 987,
    inStock: true,
    specifications: {
      'Motor': '1500W',
      'Capacity': '64 oz',
      'Blades': 'Hardened Stainless Steel',
      'Speeds': 'Variable + 5 presets',
      'Container': 'BPA-free Tritan',
      'Warranty': '10 years',
    },
    features: [
      '1500W motor for tough ingredients',
      'Variable speed control',
      '5 pre-programmed settings',
      'Self-cleaning function',
      'Hot soup capable',
      'Quiet operation',
    ],
    badge: 'new',
  },
  {
    id: 'home-006',
    name: 'Pour Over Coffee Set',
    description: 'Elegant pour-over coffee maker set with gooseneck kettle, glass carafe, and reusable filter.',
    price: 89.99,
    category: 'Home & Kitchen',
    subcategory: 'Coffee',
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 654,
    inStock: true,
    specifications: {
      'Carafe Capacity': '600ml',
      'Kettle Capacity': '1L',
      'Kettle Material': 'Stainless Steel',
      'Carafe Material': 'Borosilicate Glass',
      'Filter': 'Stainless Steel Mesh',
      'Includes': 'Carafe, kettle, filter, stand',
    },
    features: [
      'Precision gooseneck kettle',
      'Heat-resistant borosilicate glass',
      'Reusable stainless steel filter',
      'Elegant wooden stand',
      'Temperature control kettle',
      'Perfect extraction every time',
    ],
  },
  {
    id: 'home-008',
    name: 'Dyson-Style Cordless Vacuum Cleaner',
    description: 'Powerful cordless stick vacuum with advanced cyclone technology, HEPA filtration, and up to 60 minutes runtime. Perfect for whole-home cleaning.',
    price: 139.99,
    originalPrice: 449.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    images: [
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80',
      'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 3267,
    inStock: true,
    specifications: {
      'Suction Power': '150AW',
      'Runtime': 'Up to 60 minutes',
      'Dustbin Capacity': '0.77L',
      'Weight': '5.9 lbs',
      'Filtration': 'Whole-machine HEPA',
      'Charging Time': '4.5 hours',
    },
    features: [
      'Advanced cyclone technology',
      'Whole-machine HEPA filtration',
      'Converts to handheld in seconds',
      'LCD screen shows runtime and modes',
      'Anti-tangle cleaner head',
      'Wall-mounted charging dock included',
    ],
    badge: 'trending',
  },
  {
    id: 'home-010',
    name: 'Nespresso-Style Coffee Machine',
    description: 'Premium single-serve espresso machine with fast heat-up, adjustable cup sizes, and automatic shut-off. Barista-quality coffee at home.',
    price: 99.99,
    originalPrice: 299.99,
    category: 'Home & Kitchen',
    subcategory: 'Coffee',
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 2876,
    inStock: true,
    specifications: {
      'Pump Pressure': '19 Bar',
      'Heat-up Time': '25 seconds',
      'Water Tank': '34 oz (1L)',
      'Cup Sizes': 'Espresso & Lungo',
      'Dimensions': '4.3" x 12.8" x 9"',
      'Auto Shut-off': 'After 9 minutes',
    },
    features: [
      '19-bar high pressure pump',
      'Fast 25-second heat-up',
      'Two programmable cup sizes',
      'Compact space-saving design',
      'Energy efficient auto shut-off',
      'Used capsule container holds 9',
    ],
    badge: 'sale',
  },
  {
    id: 'home-011',
    name: 'Ninja-Style Professional Blender System',
    description: 'High-performance blender system with 1400-watt motor, Auto-iQ technology, and multiple containers for smoothies, food processing, and personal cups.',
    price: 119.99,
    originalPrice: 329.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    images: [
      'https://images.unsplash.com/photo-1622480916113-9000ac49b79d?w=800&q=80',
      'https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 3456,
    inStock: true,
    specifications: {
      'Motor': '1400W Peak',
      'Main Pitcher': '72 oz',
      'Processor Bowl': '64 oz',
      'Personal Cups': '2 x 16 oz',
      'Blades': 'Stacked Blade Technology',
      'Programs': '5 Auto-iQ Programs',
    },
    features: [
      'Total Crushing Technology for ice',
      'Auto-iQ intelligent programs',
      '3 speeds + pulse function',
      'Includes 72oz pitcher and personal cups',
      'BPA-free and dishwasher safe',
      'Nutri Ninja cups with to-go lids',
    ],
  },
  {
    id: 'home-012',
    name: 'Digital Air Fryer Toaster Oven',
    description: 'Large capacity air fryer toaster oven combo with 12 cooking functions, rotisserie, and dehydrator. Replaces multiple appliances.',
    price: 109.99,
    originalPrice: 349.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&q=80',
      'https://images.unsplash.com/photo-1643116774075-acc00caa9a7b?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 2198,
    inStock: true,
    specifications: {
      'Capacity': '26 Quart / 25 Liter',
      'Power': '1800W',
      'Functions': '12 Cooking Presets',
      'Temperature': '90°F - 450°F',
      'Interior': 'Non-stick, easy clean',
      'Accessories': 'Rotisserie kit, 2 racks, mesh basket',
    },
    features: [
      '12-in-1 functionality',
      'Large family-size capacity',
      'Rapid air circulation technology',
      'Digital touchscreen controls',
      'Interior light for monitoring',
      'Includes rotisserie and dehydrator accessories',
    ],
    badge: 'trending',
  },
  {
    id: 'home-013',
    name: 'Smart WiFi Instant Read Thermometer',
    description: 'Precision digital meat thermometer with Bluetooth and WiFi connectivity, app control, and preset temperatures for perfect cooking every time.',
    price: 59.99,
    originalPrice: 149.99,
    category: 'Home & Kitchen',
    subcategory: 'Gadgets',
    images: [
      'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800&q=80',
      'https://images.unsplash.com/photo-1595434091143-b375ced5fe5c?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 1567,
    inStock: true,
    specifications: {
      'Probes': '4 Color-coded Probes',
      'Range': '-40°F to 572°F',
      'Accuracy': '±0.9°F',
      'Connectivity': 'Bluetooth 5.0 + WiFi',
      'Battery': 'Rechargeable Li-ion',
      'App': 'iOS & Android',
    },
    features: [
      'Monitor from anywhere via WiFi',
      '4 probes for multiple items',
      'USDA preset temperatures',
      'Customizable alerts and alarms',
      'Magnetic base for easy storage',
      'Up to 500ft Bluetooth range',
    ],
    badge: 'new',
  },
  {
    id: 'home-015',
    name: 'Countertop Ice Maker Machine',
    description: 'Portable ice maker that produces 26 lbs of bullet ice per day. Ready in 6 minutes with self-cleaning function.',
    price: 94.99,
    originalPrice: 229.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&q=80',
      'https://images.unsplash.com/photo-1625938144755-652e08e359b7?w=800&q=80',
    ],
    rating: 4.4,
    reviewCount: 2341,
    inStock: true,
    specifications: {
      'Ice Production': '26 lbs/day',
      'Ice Ready': '6-8 minutes',
      'Ice Sizes': '2 Selectable Sizes',
      'Storage Capacity': '1.5 lbs',
      'Water Tank': '2L',
      'Dimensions': '12.3" x 9.8" x 12.8"',
    },
    features: [
      'Fast ice - ready in 6 minutes',
      '9 bullet-shaped ice cubes per cycle',
      '2 ice size options',
      'Self-cleaning function',
      'See-through window',
      'Quiet operation under 35dB',
    ],
  },
  // Office Accessories
  {
    id: 'office-001',
    name: 'Ergonomic Office Chair',
    description: 'Premium ergonomic mesh office chair with lumbar support, adjustable armrests, and breathable design.',
    price: 125.99,
    originalPrice: 499.99,
    category: 'Office Accessories',
    subcategory: 'Furniture',
    images: [
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&q=80',
      'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 2345,
    inStock: true,
    specifications: {
      'Material': 'Breathable Mesh',
      'Weight Capacity': '300 lbs',
      'Seat Height': '17" - 21"',
      'Armrests': '4D Adjustable',
      'Lumbar Support': 'Adjustable',
      'Warranty': '5 years',
    },
    features: [
      'Breathable mesh back',
      'Adjustable lumbar support',
      '4D adjustable armrests',
      'Synchro-tilt mechanism',
      'High-density foam seat',
      'Smooth-rolling casters',
    ],
    badge: 'bestseller',
  },
  {
    id: 'office-002',
    name: 'Standing Desk Electric',
    description: 'Electric height-adjustable standing desk with memory presets, cable management, and sturdy frame.',
    price: 149.99,
    category: 'Office Accessories',
    subcategory: 'Furniture',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 1678,
    inStock: true,
    specifications: {
      'Desktop Size': '60" x 30"',
      'Height Range': '25.5" - 51"',
      'Weight Capacity': '350 lbs',
      'Motor': 'Dual motor',
      'Speed': '1.5" per second',
      'Presets': '4 memory positions',
    },
    features: [
      'Dual motor for smooth lifting',
      '4 programmable height presets',
      'Anti-collision technology',
      'Built-in cable management',
      'Premium laminate desktop',
      'LED control panel',
    ],
    badge: 'trending',
  },
  {
    id: 'office-003',
    name: 'Desk Organizer Set',
    description: 'Premium bamboo desk organizer with multiple compartments for pens, files, and accessories.',
    price: 49.99,
    category: 'Office Accessories',
    subcategory: 'Organization',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 876,
    inStock: true,
    specifications: {
      'Material': 'Natural Bamboo',
      'Dimensions': '12" x 8" x 6"',
      'Compartments': '8',
      'Drawer': '1',
      'Phone Stand': 'Included',
      'Weight': '2.5 lbs',
    },
    features: [
      'Sustainable bamboo construction',
      '8 compartments for organization',
      'Built-in phone stand',
      'Letter holder section',
      'Drawer for small items',
      'Non-slip base pads',
    ],
  },
  {
    id: 'office-004',
    name: 'Monitor Arm Dual',
    description: 'Heavy-duty dual monitor arm with full range of motion and integrated cable management.',
    price: 129.99,
    category: 'Office Accessories',
    subcategory: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&q=80',
      'https://images.unsplash.com/photo-1616711906333-23cf8b9f6e78?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 1234,
    inStock: true,
    specifications: {
      'Screen Size': 'Up to 32"',
      'Weight Capacity': '22 lbs per arm',
      'VESA': '75x75, 100x100',
      'Mounting': 'Desk clamp or grommet',
      'Movement': 'Tilt, swivel, rotate, extend',
      'Material': 'Aluminum alloy',
    },
    features: [
      'Supports two monitors up to 32"',
      'Full range of motion',
      'Integrated cable management',
      'Quick-release VESA plate',
      'Gas spring for smooth adjustment',
      'Premium aluminum construction',
    ],
  },
  {
    id: 'office-005',
    name: 'LED Desk Lamp Smart',
    description: 'Smart LED desk lamp with adjustable color temperature, brightness control, and USB charging port.',
    price: 69.99,
    category: 'Office Accessories',
    subcategory: 'Lighting',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 987,
    inStock: true,
    specifications: {
      'Light Output': '1000 lumens',
      'Color Temperature': '2700K - 6500K',
      'Brightness Levels': '10',
      'USB Port': 'USB-A 5V/2A',
      'Power': '12W',
      'Arm Reach': '20"',
    },
    features: [
      'Adjustable color temperature',
      '10 brightness levels',
      'USB charging port',
      'No flicker, no blue light hazard',
      'Touch controls',
      'Memory function',
    ],
    badge: 'new',
  },
  {
    id: 'office-006',
    name: 'Laptop Stand Adjustable',
    description: 'Aluminum laptop stand with adjustable height and angle for better ergonomics and cooling.',
    price: 59.99,
    category: 'Office Accessories',
    subcategory: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1527434284607-8fca70b3da7a?w=800&q=80',
      'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 2134,
    inStock: true,
    specifications: {
      'Material': 'Aluminum Alloy',
      'Compatibility': '10" - 17" laptops',
      'Height Range': '5.9" - 10.6"',
      'Angle Range': '0° - 45°',
      'Weight Capacity': '44 lbs',
      'Weight': '1.5 lbs',
    },
    features: [
      'Premium aluminum construction',
      'Adjustable height and angle',
      'Improved ventilation',
      'Non-slip silicone pads',
      'Foldable for portability',
      'Compatible with all laptops',
    ],
  },
  // Travel Accessories
  {
    id: 'travel-001',
    name: 'Smart Carry-On Luggage',
    description: 'Premium hardshell carry-on with built-in USB charger, TSA lock, and 360° spinner wheels.',
    price: 99.99,
    category: 'Travel Accessories',
    subcategory: 'Luggage',
    images: [
      'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=800&q=80',
      'https://images.unsplash.com/photo-1581553680321-4fffff48f066?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 1876,
    inStock: true,
    specifications: {
      'Dimensions': '22" x 14" x 9"',
      'Weight': '7.5 lbs',
      'Material': 'Polycarbonate',
      'Lock': 'TSA-approved',
      'Wheels': '360° spinner',
      'USB': 'Built-in USB port',
    },
    features: [
      'Built-in USB charging port',
      'TSA-approved combination lock',
      '360° silent spinner wheels',
      'Scratch-resistant shell',
      'Expandable design',
      'Interior compression system',
    ],
    badge: 'bestseller',
  },
  {
    id: 'travel-002',
    name: 'Travel Backpack 40L',
    description: 'Versatile travel backpack with laptop compartment, anti-theft design, and expandable capacity.',
    price: 89.99,
    category: 'Travel Accessories',
    subcategory: 'Bags',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
      'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 2345,
    inStock: true,
    specifications: {
      'Capacity': '40L (expandable to 50L)',
      'Laptop Fit': 'Up to 17"',
      'Material': 'Water-resistant Polyester',
      'Dimensions': '22" x 14" x 9"',
      'Weight': '3.2 lbs',
      'Pockets': '15+',
    },
    features: [
      'Expandable 40L to 50L capacity',
      'Fits 17" laptop with padding',
      'Anti-theft back panel',
      'Water-resistant material',
      'USB charging port',
      'Luggage strap',
    ],
    badge: 'trending',
  },
  {
    id: 'travel-003',
    name: 'Packing Cube Set 6-Piece',
    description: 'Lightweight compression packing cubes in various sizes for organized and efficient packing.',
    price: 39.99,
    category: 'Travel Accessories',
    subcategory: 'Organization',
    images: [
      'https://images.unsplash.com/photo-1553531889-e6cf4d692b1b?w=800&q=80',
      'https://images.unsplash.com/photo-1520006403909-838d6b92c22e?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 3456,
    inStock: true,
    specifications: {
      'Pieces': '6 (2 large, 2 medium, 2 small)',
      'Material': 'Ripstop Nylon',
      'Features': 'Compression zippers',
      'See-through': 'Mesh top panel',
      'Weight': '0.8 lbs total',
      'Colors': 'Multiple available',
    },
    features: [
      '6 cubes in various sizes',
      'Double compression zippers',
      'See-through mesh panels',
      'Lightweight ripstop nylon',
      'Water-resistant coating',
      'Carrying handle on each cube',
    ],
  },
  {
    id: 'travel-004',
    name: 'Universal Travel Adapter',
    description: 'All-in-one international travel adapter with USB-C PD and multiple USB ports.',
    price: 44.99,
    category: 'Travel Accessories',
    subcategory: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1622675363311-3e1904dc1885?w=800&q=80',
      'https://images.unsplash.com/photo-1615526675159-e248c3021d3f?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 1567,
    inStock: true,
    specifications: {
      'Compatibility': '200+ countries',
      'USB-C PD': '30W',
      'USB-A Ports': '3 (5V/2.4A each)',
      'AC Outlet': '1 (up to 2000W)',
      'Safety': 'Built-in fuse, child safety',
      'Weight': '150g',
    },
    features: [
      'Works in 200+ countries',
      '30W USB-C Power Delivery',
      '3 USB-A quick charge ports',
      'Built-in safety fuse',
      'Child safety shutters',
      'Compact and portable',
    ],
    badge: 'new',
  },
  {
    id: 'travel-005',
    name: 'Neck Pillow Memory Foam',
    description: 'Premium memory foam travel pillow with adjustable clasp and machine-washable cover.',
    price: 34.99,
    category: 'Travel Accessories',
    subcategory: 'Comfort',
    images: [
      'https://images.unsplash.com/photo-1520219306100-ec4afeeefe58?w=800&q=80',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 2876,
    inStock: true,
    specifications: {
      'Material': 'Memory Foam',
      'Cover': 'Velvet + Breathable Mesh',
      'Clasp': 'Adjustable magnetic',
      'Carry': 'Snap loop attachment',
      'Washable': 'Machine-washable cover',
      'Size': 'One size fits most',
    },
    features: [
      'Premium memory foam support',
      'Adjustable clasp design',
      'Breathable mesh side',
      'Machine-washable cover',
      'Snap loop for easy carrying',
      'Ergonomic 360° support',
    ],
  },
  {
    id: 'travel-006',
    name: 'Digital Luggage Scale',
    description: 'Compact digital luggage scale with LED display and auto-lock weight reading.',
    price: 19.99,
    category: 'Travel Accessories',
    subcategory: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=800&q=80',
      'https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=800&q=80',
    ],
    rating: 4.4,
    reviewCount: 1234,
    inStock: true,
    specifications: {
      'Capacity': '110 lbs / 50 kg',
      'Accuracy': '±0.1 lb / 50g',
      'Display': 'LED backlit',
      'Units': 'lb, kg, oz',
      'Power': 'CR2032 battery',
      'Auto-off': '60 seconds',
    },
    features: [
      'Weighs up to 110 lbs',
      'High precision sensor',
      'LED backlit display',
      'Auto-lock weight reading',
      'Tare function',
      'Compact and lightweight',
    ],
  },
  // Fitness Equipment
  {
    id: 'fitness-001',
    name: 'Smart Resistance Bands Set',
    description: 'Digital resistance bands with real-time feedback, workout tracking, and app connectivity.',
    price: 129.99,
    category: 'Fitness Equipment',
    subcategory: 'Strength',
    images: [
      'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&q=80',
      'https://images.unsplash.com/photo-1517130038641-a774d04afb3c?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 876,
    inStock: true,
    specifications: {
      'Bands': '5 resistance levels (5-150 lbs)',
      'Sensor': 'Built-in force sensor',
      'App': 'iOS & Android',
      'Battery': 'Rechargeable, 30-day',
      'Includes': 'Handles, door anchor, ankle straps',
      'Material': 'Natural latex',
    },
    features: [
      'Real-time rep counting',
      'Force measurement tracking',
      'Guided workout programs',
      '5 resistance levels',
      'Premium natural latex',
      'Full accessory kit included',
    ],
    badge: 'new',
  },
  {
    id: 'fitness-002',
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells ranging from 5-52.5 lbs with quick-change dial system.',
    price: 149.99,
    originalPrice: 399.99,
    category: 'Fitness Equipment',
    subcategory: 'Strength',
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
      'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 1567,
    inStock: true,
    specifications: {
      'Weight Range': '5 - 52.5 lbs each',
      'Increments': '2.5 lbs',
      'Adjustment': 'Dial system',
      'Material': 'Steel with rubber coating',
      'Dimensions': '16.5" x 8" x 9"',
      'Includes': 'Pair of dumbbells + trays',
    },
    features: [
      'Replaces 15 sets of weights',
      'Quick 2-second adjustment',
      'Smooth dial mechanism',
      'Durable steel construction',
      'Rubber coating for grip',
      'Compact storage trays',
    ],
    badge: 'bestseller',
  },
  {
    id: 'fitness-003',
    name: 'Yoga Mat Premium',
    description: 'Extra thick eco-friendly yoga mat with alignment lines and non-slip surface.',
    price: 69.99,
    category: 'Fitness Equipment',
    subcategory: 'Yoga',
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80',
      'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 2345,
    inStock: true,
    specifications: {
      'Thickness': '6mm',
      'Dimensions': '72" x 26"',
      'Material': 'Natural rubber + PU',
      'Features': 'Alignment lines',
      'Surface': 'Non-slip both sides',
      'Weight': '5.5 lbs',
    },
    features: [
      'Extra thick 6mm cushioning',
      'Alignment guide lines',
      'Dual non-slip surfaces',
      'Eco-friendly materials',
      'Free from latex and PVC',
      'Includes carrying strap',
    ],
    badge: 'trending',
  },
  {
    id: 'fitness-004',
    name: 'Jump Rope Smart',
    description: 'Digital jump rope with LCD display showing jumps, calories, and timer.',
    price: 29.99,
    category: 'Fitness Equipment',
    subcategory: 'Cardio',
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 1876,
    inStock: true,
    specifications: {
      'Display': 'LCD with backlight',
      'Tracking': 'Jumps, calories, time',
      'Rope Length': 'Adjustable (up to 9.8 ft)',
      'Rope Material': 'PVC with steel core',
      'Handle': 'Foam grip',
      'Battery': '2x AAA',
    },
    features: [
      'Digital jump counter',
      'Calorie burn tracking',
      'Built-in timer',
      'Adjustable rope length',
      'Steel core for durability',
      'Comfortable foam handles',
    ],
  },
  {
    id: 'fitness-005',
    name: 'Foam Roller Set',
    description: 'Muscle recovery foam roller set with varying densities for deep tissue massage.',
    price: 44.99,
    category: 'Fitness Equipment',
    subcategory: 'Recovery',
    images: [
      'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80',
      'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 1234,
    inStock: true,
    specifications: {
      'Pieces': '3 (18" roller, massage ball, stick)',
      'Roller Density': 'High-density EVA',
      'Ball Size': '5" diameter',
      'Stick Length': '17"',
      'Material': 'EVA foam',
      'Includes': 'Carrying bag + guide',
    },
    features: [
      '3-piece recovery set',
      'Textured for deep massage',
      'High-density EVA foam',
      'Targets trigger points',
      'Includes exercise guide',
      'Portable carrying bag',
    ],
  },
  {
    id: 'fitness-006',
    name: 'Kettlebell Adjustable',
    description: 'Space-saving adjustable kettlebell with weight range from 5-40 lbs.',
    price: 149.99,
    category: 'Fitness Equipment',
    subcategory: 'Strength',
    images: [
      'https://images.unsplash.com/photo-1517344884509-a0c97ec11bcc?w=800&q=80',
      'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 876,
    inStock: true,
    specifications: {
      'Weight Range': '5 - 40 lbs',
      'Increments': '5 lbs',
      'Adjustment': 'Quick-lock dial',
      'Material': 'Cast iron + rubber',
      'Handle': 'Wide ergonomic',
      'Base': 'Storage tray included',
    },
    features: [
      'Replaces 8 kettlebells',
      'Quick weight adjustment',
      'Wide ergonomic handle',
      'Rubber-coated weights',
      'Stable storage base',
      'Compact design',
    ],
    badge: 'sale',
  },
  // Lifestyle Products
  {
    id: 'lifestyle-001',
    name: 'Premium Leather Wallet',
    description: 'Handcrafted genuine leather bifold wallet with RFID blocking and multiple card slots.',
    price: 79.99,
    category: 'Lifestyle Products',
    subcategory: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
      'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 2134,
    inStock: true,
    specifications: {
      'Material': 'Full-grain Leather',
      'Card Slots': '8',
      'Bill Compartments': '2',
      'ID Window': 'Yes',
      'RFID': 'Blocking enabled',
      'Dimensions': '4.5" x 3.5" x 0.5"',
    },
    features: [
      'Genuine full-grain leather',
      'RFID blocking protection',
      '8 card slots',
      '2 bill compartments',
      'ID window',
      'Slim profile design',
    ],
    badge: 'bestseller',
  },
  {
    id: 'lifestyle-002',
    name: 'Minimalist Watch Classic',
    description: 'Elegant minimalist watch with Swiss movement, sapphire crystal, and interchangeable straps.',
    price: 139.99,
    originalPrice: 249.99,
    category: 'Lifestyle Products',
    subcategory: 'Watches',
    images: [
      'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 1567,
    inStock: true,
    specifications: {
      'Movement': 'Swiss Quartz',
      'Case': '40mm Stainless Steel',
      'Crystal': 'Sapphire',
      'Water Resistance': '5 ATM',
      'Strap': 'Italian Leather',
      'Warranty': '2 years',
    },
    features: [
      'Swiss quartz movement',
      'Scratch-resistant sapphire',
      'Stainless steel case',
      'Italian leather strap',
      'Quick-release strap system',
      'Water resistant to 50m',
    ],
    badge: 'sale',
  },
  {
    id: 'lifestyle-003',
    name: 'Sunglasses Polarized Premium',
    description: 'Designer polarized sunglasses with UV400 protection and lightweight titanium frame.',
    price: 149.99,
    category: 'Lifestyle Products',
    subcategory: 'Eyewear',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
      'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&q=80',
    ],
    rating: 4.6,
    reviewCount: 987,
    inStock: true,
    specifications: {
      'Frame': 'Titanium',
      'Lens': 'Polarized TAC',
      'UV Protection': 'UV400',
      'Weight': '22g',
      'Includes': 'Case, cleaning cloth',
      'Warranty': '1 year',
    },
    features: [
      'Polarized lenses',
      '100% UV400 protection',
      'Lightweight titanium frame',
      'Anti-glare coating',
      'Spring hinges',
      'Premium hard case',
    ],
    badge: 'trending',
  },
  {
    id: 'lifestyle-004',
    name: 'Insulated Water Bottle',
    description: 'Triple-insulated stainless steel water bottle keeping drinks cold 24hrs or hot 12hrs.',
    price: 39.99,
    category: 'Lifestyle Products',
    subcategory: 'Drinkware',
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80',
      'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&q=80',
    ],
    rating: 4.8,
    reviewCount: 3456,
    inStock: true,
    specifications: {
      'Capacity': '32 oz / 1L',
      'Insulation': 'Triple-wall vacuum',
      'Material': '18/8 Stainless Steel',
      'Lid': 'Leak-proof flex cap',
      'Mouth': 'Wide mouth',
      'BPA': 'Free',
    },
    features: [
      'Cold 24 hours, hot 12 hours',
      'Triple-wall insulation',
      '18/8 food-grade steel',
      'Leak-proof lid',
      'Wide mouth for ice',
      'Powder-coated finish',
    ],
    badge: 'new',
  },
  {
    id: 'lifestyle-005',
    name: 'Leather Messenger Bag',
    description: 'Vintage-style genuine leather messenger bag with padded laptop compartment.',
    price: 109.99,
    category: 'Lifestyle Products',
    subcategory: 'Bags',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
      'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&q=80',
    ],
    rating: 4.7,
    reviewCount: 876,
    inStock: true,
    specifications: {
      'Material': 'Buffalo Leather',
      'Laptop Fit': 'Up to 15.6"',
      'Dimensions': '16" x 12" x 4"',
      'Strap': 'Adjustable shoulder',
      'Pockets': '5 compartments',
      'Closure': 'Magnetic snap + buckle',
    },
    features: [
      'Genuine buffalo leather',
      'Padded laptop sleeve',
      'Vintage distressed look',
      'Adjustable shoulder strap',
      'Multiple compartments',
      'Brass hardware',
    ],
  },
  {
    id: 'lifestyle-006',
    name: 'Aromatherapy Diffuser',
    description: 'Ultrasonic essential oil diffuser with ambient lighting and auto shut-off.',
    price: 49.99,
    category: 'Lifestyle Products',
    subcategory: 'Home',
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
      'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=800&q=80',
    ],
    rating: 4.5,
    reviewCount: 2134,
    inStock: true,
    specifications: {
      'Capacity': '500ml',
      'Coverage': 'Up to 500 sq ft',
      'Runtime': '10 hours',
      'Mist Output': 'Adjustable',
      'Light': '7 LED colors',
      'Timer': '1, 3, 6 hours',
    },
    features: [
      'Ultrasonic technology',
      '500ml large capacity',
      '7 ambient light colors',
      'Timer settings',
      'Auto shut-off',
      'Whisper quiet operation',
    ],
  },
]

export const categories = [
  {
    name: 'Electronics',
    slug: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    description: 'Premium audio, monitors, and accessories',
    productCount: 6,
  },
  {
    name: 'Smart Gadgets',
    slug: 'smart-gadgets',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    description: 'Connected devices for modern living',
    productCount: 5,
  },
  {
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    description: 'Appliances and cookware',
    productCount: 11,
  },
  {
    name: 'Office Accessories',
    slug: 'office-accessories',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
    description: 'Ergonomic furniture and desk essentials',
    productCount: 6,
  },
  {
    name: 'Travel Accessories',
    slug: 'travel-accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    description: 'Luggage and travel essentials',
    productCount: 6,
  },
  {
    name: 'Fitness Equipment',
    slug: 'fitness-equipment',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    description: 'Home workout and recovery gear',
    productCount: 6,
  },
  {
    name: 'Lifestyle Products',
    slug: 'lifestyle-products',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80',
    description: 'Accessories and everyday essentials',
    productCount: 6,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category.toLowerCase().replace(/\s+/g, '-') === category.toLowerCase() || p.category === category)
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.badge === 'bestseller')
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.badge === 'new')
}

export function getTrendingProducts(): Product[] {
  return products.filter((p) => p.badge === 'trending')
}

export function getSaleProducts(): Product[] {
  return products.filter((p) => p.badge === 'sale')
}

export function getRelatedProducts(productId: string, limit: number = 4): Product[] {
  const product = getProductById(productId)
  if (!product) return []
  
  return products
    .filter((p) => p.category === product.category && p.id !== productId)
    .slice(0, limit)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.category.toLowerCase().includes(lowercaseQuery) ||
      p.subcategory.toLowerCase().includes(lowercaseQuery)
  )
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge).slice(0, 8)
}
